eksctl create cluster \
--name eks-db-poc \
--version 1.16 \
--region eu-central-1 \
--nodegroup-name ng-linux-workers \
--node-type t3.small \
--nodes 2 \
--nodes-min 1 \
--nodes-max 4 \
--ssh-access \
--ssh-public-key ~/.ssh/ffm-keypair.pub \
--managed
