apiVersion: v1
kind: Pod
metadata:
  name: pg-dump
spec:
  containers:
  - name: pg-dump
    image: 899147897464.dkr.ecr.eu-central-1.amazonaws.com/pg-dump:latest
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
    - name: secrets
      mountPath: /root
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
  - name: secrets
    secret:
      secretName: pgpassword
      defaultMode: 0400
